channels:
- conda-forge
dependencies:
- python=3.8.13
- pip<=21.3.1
- pip:
  - mlflow
  - pandas==1.4.2
  - psutil==5.8.0
  - scikit-learn==1.0.2
  - typing-extensions==3.10.0.2
  - xgboost==1.6.0
name: mlflow-env
